name: dating_app
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8
  sms_autofill: ^2.2.0
  image_picker: ^0.8.5+3
  dotted_border: ^2.0.0
  intl_phone_field: ^3.0.0
  flutter_svg: ^2.0.9
  flutter_sound: ^9.2.13
  path_provider_android: ^2.2.15
  audio_waveforms: ^1.2.0
  path_provider: ^2.0.14
  intl: ^0.18.0
  agora_rtc_engine: ^6.0.0  # Latest version at the time
  permission_handler: ^11.0.0  # For microphone and camera permissions
  google_maps_flutter: ^2.11.0
  geocoding: ^3.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  # Adding assets for the project
  assets:
    - assets/image@2x (1).jpg
    - assets/Pairup (1) 1.jpg
    - assets/Pairup 1@2x.jpg
    - assets/Pairup (1) 3.jpg
    - assets/Pairup 1.svg
    - assets/Pairup (1) aa.jpg
    - assets/profileimage.png

